import type { Metadata } from "next"

import "../config/globals.css"
import NextAuthProvider from "@/config/provider/next-auth"
import QueryProvider from "@/config/provider/react-query"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body>
				<NextAuthProvider>
					<QueryProvider>{children}</QueryProvider>
				</NextAuthProvider>
			</body>
		</html>
	)
}
