import type { Metadata } from "next"

import "../config/globals.css"

import QueryProvider from "@/common/provider/queryProvider"
import NextAuthProvider from "@/features/auth/provider/nextAuthProvider"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body>
				<NextAuthProvider>
					<QueryProvider>{children}</QueryProvider>
				</NextAuthProvider>
			</body>
		</html>
	)
}
